source 'https://github.com/CocoaPods/Specs.git'

inhibit_all_warnings!

target 'contentful-ios-dialogs', :exclusive => true do
  pod "ContentfulDialogs", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "ContentfulDialogs", :path => "../"
end
